name: Validate PR

on: [pull_request_target]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      
      - name: Set base branch and PR info
        run: |
          echo "chekcout completed."

      - name: Exec
        run: |
          ./echo.sh
        env:
          GH_TOKEN: ${{ github.token }}
        